"""Initial tables creation

Revision ID: 262305f91666
Revises: 
Create Date: 2026-09-15 14:27:00.492667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262305f91666'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('engineering_system_type', sa.Text(), nullable=True),
    sa.Column('sensor_type', sa.Text(), nullable=True),
    sa.Column('engineering_system_tag', sa.Text(), nullable=True),
    sa.Column('sensor_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channels_sensor_type', 'channels', ['sensor_type'], unique=False)
    op.create_index('idx_channels_system_type', 'channels', ['engineering_system_type'], unique=False)
    op.create_index('idx_channels_tag', 'channels', ['engineering_system_tag'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('dispatch_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objects_parent_id', 'objects', ['parent_id'], unique=False)
    op.create_index('idx_objects_type', 'objects', ['object_type'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('event_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_alarm', sa.Boolean(), nullable=False),
    sa.Column('sensor_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='fk_events_channel'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_alarm_time', 'events', ['event_at'], unique=False, postgresql_where=sa.text('is_alarm = true'))
    op.create_index('idx_events_channel_time', 'events', ['channel_id', 'event_at'], unique=False)
    op.create_index('idx_events_event_at', 'events', ['event_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_event_at', table_name='events')
    op.drop_index('idx_events_channel_time', table_name='events')
    op.drop_index('idx_events_alarm_time', table_name='events', postgresql_where=sa.text('is_alarm = true'))
    op.drop_table('events')
    op.drop_index('idx_objects_type', table_name='objects')
    op.drop_index('idx_objects_parent_id', table_name='objects')
    op.drop_table('objects')
    op.drop_index('idx_channels_tag', table_name='channels')
    op.drop_index('idx_channels_system_type', table_name='channels')
    op.drop_index('idx_channels_sensor_type', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
