"""add tables for mk_sensors user project

Revision ID: 75c03db184ee
Revises: c49e72b138d5
Create Date: 2026-09-22 15:28:54.751260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c03db184ee'
down_revision: Union[str, Sequence[str], None] = 'c49e72b138d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_email'), 'auth', ['email'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('channels', sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    op.add_column('channels', sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    op.add_column('objects', sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    op.add_column('objects', sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM now())::bigint'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'updated_at')
    op.drop_column('objects', 'created_at')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('channels', 'updated_at')
    op.drop_column('channels', 'created_at')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_auth_email'), table_name='auth')
    op.drop_table('auth')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
